### ISSUE TITLE
Starting app fails with "Error: Cannot find module '@babel/plugin-proposal-function-bind' "

### ISSUE THREAD

**Issue by ksuess** [plone/create-volto-app#18]
### Steps to reproduce

Create volto app with
```
npx @plone/create-volto-app my-volto-app
```
This installs @plone/volto 4.0.0-alpha.18

Starting the app with
```
cd my-volto-app/
RAZZLE_API_PATH=http://localhost:8081/Plone PORT=3017 yarn start
```
fails with

```
Module build failed (from ./node_modules/babel-loader/lib/index.js)
Error: Cannot find module '@babel/plugin-proposal-function-bind' from '/Users/ksuess/Volto/hands-on-katja/my-volto-app'
```
The directories of node_modules seem to be different than in installation with earlier versions of @plone/volto
![image](https://user-images.githubusercontent.com/1144737/70848101-efff2b00-1e6c-11ea-9299-20730451fee0.png)

**Comment by ksuess** [comment]
As soon as I downgrade to @plone/volto 4.0.0-alpha.15, the app is starting up fine.

**Comment by ksuess** [comment]
Dear Victor / @sneridagh 
It would be great to follow your volto hands-on training with the current pre release of volto. Would you please be so kind and have a look at create-volto-app. The app is starting throwing an errror. 
Your pre release of create-volto-app since I posted this issue does not change situation.

Thank you!

**Comment by sneridagh** [comment]
@ksuess I am aware of it, unfortunately I haven't time to take a look into it yet :( Sorry for the inconvenience... For now, try to use the training repo with the alpha version that I used when I wrote it. I will try to find some time to fix it.

/cc @robgietema

**Comment by sneridagh** [comment]
@ksuess https://github.com/collective/volto-hands-on-training

**Comment by sneridagh** [comment]
@ksuess I fixed it for now using a good known "old" `yarn.lock` and including it in the project template. 

`npx @plone/create-volto-app@alpha my-volto-project` should work now.

However, I recommend that for the first steps, use the repo if you are doing the training, and specially use the `api` Plone buildout you'll find there because it has all the Plone requirements and dependencies to run Volto.

I've opened #19 to follow and fix the real problem of the issue.
